Models/Coche.cs
namespace NetCoreLinqToSqlInjection.Models
{
    public class Coche : ICoche
    {
        public string Marca { get; set; }   

        public string Modelo { get; set;}

        public string Imagen { get; set;}

        public int Velocidad { get; set;}

        public int VelocidadMaxima { get; set;}

        public Coche()
        {
            this.Marca = "Utilitario";
            this.Modelo = "22b";
            this.Imagen = "imagen.png";
            this.Velocidad = 0;
            this.VelocidadMaxima = 140;
        }

        public int Acelerar()
        {
            this.Velocidad += 20;
            if(this.Velocidad >= this.VelocidadMaxima)
            {
                this.Velocidad = this.VelocidadMaxima;
            }

            return this.Velocidad;
        }
        public int Frenar()
        {
            this.Velocidad -= 20;
            if (this.Velocidad <= 0)
            {
                this.Velocidad = 0;
            }

            return this.Velocidad;
        }

    }
}

Models/Deportivo.cs
namespace NetCoreLinqToSqlInjection.Models
{
    public class Deportivo : ICoche
    {

        public Deportivo()
        {
            this.Marca = "ferrari";
            this.Modelo = "260ITALIA";
            this.Imagen = "dios.jpg";
            this.Velocidad = 0;
            this.VelocidadMaxima = 400;
        }

        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Imagen { get; set; }
        public int Velocidad { get; set; }
        public int VelocidadMaxima { get; set; }


        public int Acelerar()
        {
            this.Velocidad += 60;
            if (this.Velocidad >= this.VelocidadMaxima)
            {
                this.Velocidad = this.VelocidadMaxima;
            }

            return this.Velocidad;
        }
        public int Frenar()
        {
            this.Velocidad -= 30;
            if (this.Velocidad <= 0)
            {
                this.Velocidad = 0;
            }

            return this.Velocidad;
        }
    }
}

Models/Doctor.cs
namespace NetCoreLinqToSqlInjection.Models
{
    public class Doctor
    {

        public int IdDoctor { get; set; }   
        public string Apellido { get; set; }

        public string Especialidad { get; set;}

        public int Salario { get; set;}

        public int IdHospital { get; set;}  

    }
}

Models/ErrorViewModel.cs
namespace NetCoreLinqToSqlInjection.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ICoche.cs
namespace NetCoreLinqToSqlInjection.Models
{
    public interface ICoche
    {
        public string Marca { get; set; }

        public string Modelo { get; set; }

        public string Imagen { get; set; }

        public int Velocidad { get; set; }

        public int VelocidadMaxima { get; set; }

        int Acelerar();

        int Frenar();

    }
}

Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreLinqToSqlInjection.Models;

namespace NetCoreLinqToSqlInjection.Controllers
{
    public class CochesController : Controller
    {
        
        private ICoche car;

        public CochesController(ICoche coche)
        {
            this.car = coche;
        }

        public IActionResult Index()
        {
            return View(this.car);
        }

        [HttpPost]
        public IActionResult Index(string accion)
        {
            if(accion.ToLower()== "acelerar")
            {
                this.car.Acelerar();
            }

           else
            {
                this.car.Frenar();
            }

            return View(this.car);
        }
    }
}

Controllers/DoctoresController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreLinqToSqlInjection.Models;
using NetCoreLinqToSqlInjection.Repositories;

namespace NetCoreLinqToSqlInjection.Controllers
{
    public class DoctoresController : Controller

    {
        private IRepositoryDoctores repo;
        public DoctoresController(IRepositoryDoctores repo)

        {
            this.repo = repo;
        }

        public IActionResult Index()

        {
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }

        public IActionResult Create()

        {
            return View();
        }

        [HttpPost]

        public IActionResult Create(Doctor doctor)

        {
            this.repo.InsertDoctor(doctor.IdDoctor, doctor.Apellido, doctor.Especialidad

                , doctor.Salario, doctor.IdHospital);

            return RedirectToAction("Index");

        }

        public IActionResult DoctoresEspecialidad()
        {
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);  
        }

        [HttpPost]
        public IActionResult DoctoresEspecialidad(string especialidad)
        {
            List<Doctor> doctores = this.repo.GetDoctoresEspecialidad(especialidad);
            if(doctores == null)
            {
                ViewData["MENSAJE"] = "No hay doctores"
                    + especialidad;
                return View();

            }
            else
            {
                return View(doctores);
            }

        }



        public IActionResult Delete(int iddoctor)
        {
            this.repo.DeleteDoctor(iddoctor);   
            return RedirectToAction("Index");
        }

        public IActionResult UpdateDoctor()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UpdateDoctor(int iddoctor)
        {
            this.repo.UpdateDoctor(iddoctor);
            ViewData["MENSAJE"] = "Doctor actualizado!!";
            return RedirectToAction("Index");
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreLinqToSqlInjection.Models;
using System.Diagnostics;

namespace NetCoreLinqToSqlInjection.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Coches/Index.cshtml
@model ICoche

<h1> Dependencia </h1>

<h1> @Model.Marca , @Model.Modelo</h1>

<img src="~/images/@Model.Imagen" style="width :500px; height: 300px" />

<h2> Velocidad Actual : @Model.Velocidad</h2>

<h2> Velocidad Maxima : @Model.VelocidadMaxima</h2>

<form method="post">
    <button name="accion" value ="acelerar" class="btn btn-dark"> 
        Acelerar
        </button>

    <button name="accion" value="frenar" class="btn btn-dark">
        Frenar
    </button>


</form>

Views/Doctores/Create.cshtml
<h1>New Doctor</h1>

<p>

    <a asp-controller="Doctores"
       asp-action="Index">

        Back to Index

    </a>
</p>



<form method="post">

    <label>Id Doctor</label>
    <input type="number" class="form-control"
           name="iddoctor" />
    <label>Apellido</label>
    <input type="text" name="apellido" class="form-control" />
    <label>Especialidad</label>
    <input type="text" name="especialidad" class="form-control" />
    <label>Salario</label>
    <input type="number" name="salario" class="form-control" />
    <label>Id Hospital</label>
    <input type="number" name="idhospital" class="form-control" />
    <button class="btn btn-info">

        Create Doctor

    </button>

</form> 

Views/Doctores/DoctoresEspecialidad.cshtml
@model List<Doctor>

<h1> Docrtores Especialidad IoC</h1>

<form method="post">
    <label> Especialidad</label>
    <input type ="text" name="especialidad" class="form-control" required />
    <button class="btn btn-dark">
        Buscar Doctores
    </button>
</form>

<h2> @ViewData["MENSAJE"]</h2>
@if(Model != null){

    <table class="table table-bordered">

        <thead>
            <tr>
                <th>Apellido</th>
                <th>Especialidad</th>
                <th>Salario</th>
                <th>Hospital</th>
            </tr>
        </thead>

        <tbody>

            @foreach (Doctor doc in Model)
            {
                <tr>

                    <td>@doc.Apellido</td>
                    <td>@doc.Especialidad</td>
                    <td>@doc.Salario</td>
                    <td>@doc.IdHospital</td>
                </tr>
            }
        </tbody>

    </table>
}

Views/Doctores/Index.cshtml
@model List<Doctor>



<h1>Doctores Dependency Injection</h1>


<p>

    <a asp-controller="Doctores"
       asp-action="Create">

        Crear Doctor

    </a>
</p>


<p>

    <a asp-controller="Doctores"
       asp-action="DoctoresEspecialidad">

        Buscar

    </a>
</p>

<table class="table table-bordered">

    <thead>
        <tr>
            <th>Apellido</th>
            <th>Especialidad</th>
            <th>Salario</th>
            <th>Hospital</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </tr>
    </thead>

    <tbody>

        @foreach (Doctor doc in Model)
        {
            <tr>

                <td>@doc.Apellido</td>
                <td>@doc.Especialidad</td>
                <td>@doc.Salario</td>
                <td>@doc.IdHospital</td>
                <td>
                    <a asp-controller="Doctores"
                       asp-action="UpdateDoctor" asp-route-iddoctor="@doc.IdDoctor">
                        Edit
                    </a>
                </td>
                <td>
                    <a asp-controller="Doctores"
                       asp-action="Delete" asp-route-iddoctor ="@doc.IdDoctor"> 
                   Delete
                   </a>
                </td>
            </tr>
        }
    </tbody>

</table> 

Views/Doctores/UpdateDoctor.cshtml
@model Doctor

<h1>New Doctor</h1>

<p>

    <a asp-controller="Doctores"
       asp-action="Index">

        Back to Index

    </a>
</p>



<form method="post">

    <label>Id Doctor</label>
    <input type="number" class="form-control"
           name="iddoctor" />
    <label>Apellido</label>
    <input type="text" name="apellido" class="form-control" value="@Model.Apellido  />
    <label>Especialidad</label>
    <input type="text" name="especialidad" class="form-control" value="@Model.IdHospital />
    <label>Salario</label>
    <input type="number" name="salario" class="form-control" value="@Model.Especialidad  />
    <label>Id Hospital</label>
    <input type="number" name="idhospital" class="form-control" value="@Model.Salario  />
    <button class="btn btn-info">

        Create Doctor

    </button>

</form> 

<h1> @ViewData["MENSAJE"]</h1>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreLinqToSqlInjection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetCoreLinqToSqlInjection.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCoreLinqToSqlInjection</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coches" asp-action="Index">Coches</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctores" asp-action="Index">Doctores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NetCoreLinqToSqlInjection - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>